const myData = [
  {
    name: "John Doe",
    age: 25,
    gender: "Male",
    class: 12,
    rollNo: 101,
    email: "john.doe@example.com",
    address: "123 Main Street, Cityville",
    phoneNumber: "123-456-7890",
  },
  {
    name: "Alice Smith",
    age: 22,
    gender: "Female",
    class: 11,
    rollNo: 202,
    email: "alice.smith@example.com",
    address: "456 Oak Avenue, Townsville",
    phoneNumber: "987-654-3210",
  },
  {
    name: "Bob Johnson",
    age: 28,
    gender: "Male",
    class: 10,
    rollNo: 303,
    email: "bob.johnson@example.com",
    address: "789 Pine Lane, Villagetown",
    phoneNumber: "456-789-0123",
  },
  {
    name: "Eva Martinez",
    age: 24,
    gender: "Female",
    class: 12,
    rollNo: 404,
    email: "eva.martinez@example.com",
    address: "567 Cedar Street, Hamletville",
    phoneNumber: "789-012-3456",
  },
  {
    name: "John Doe",
    age: 25,
    gender: "Male",
    class: 12,
    rollNo: 101,
    email: "john.doe@example.com",
    address: "123 Main Street, Cityville",
    phoneNumber: "123-456-7890",
  },
  {
    name: "Alice Smith",
    age: 22,
    gender: "Female",
    class: 11,
    rollNo: 202,
    email: "alice.smith@example.com",
    address: "456 Oak Avenue, Townsville",
    phoneNumber: "987-654-3210",
  },
  {
    name: "Bob Johnson",
    age: 28,
    gender: "Male",
    class: 10,
    rollNo: 303,
    email: "bob.johnson@example.com",
    address: "789 Pine Lane, Villagetown",
    phoneNumber: "456-789-0123",
  },
  {
    name: "Eva Martinez",
    age: 24,
    gender: "Female",
    class: 12,
    rollNo: 404,
    email: "eva.martinez@example.com",
    address: "567 Cedar Street, Hamletville",
    phoneNumber: "789-012-3456",
  },
  {
    name: "John Doe",
    age: 25,
    gender: "Male",
    class: 12,
    rollNo: 101,
    email: "john.doe@example.com",
    address: "123 Main Street, Cityville",
    phoneNumber: "123-456-7890",
  },
  {
    name: "Alice Smith",
    age: 22,
    gender: "Female",
    class: 11,
    rollNo: 202,
    email: "alice.smith@example.com",
    address: "456 Oak Avenue, Townsville",
    phoneNumber: "987-654-3210",
  },
  {
    name: "Bob Johnson",
    age: 28,
    gender: "Male",
    class: 10,
    rollNo: 303,
    email: "bob.johnson@example.com",
    address: "789 Pine Lane, Villagetown",
    phoneNumber: "456-789-0123",
  },
  {
    name: "Eva Martinez",
    age: 24,
    gender: "Female",
    class: 12,
    rollNo: 404,
    email: "eva.martinez@example.com",
    address: "567 Cedar Street, Hamletville",
    phoneNumber: "789-012-3456",
  },
  {
    name: "John Doe",
    age: 25,
    gender: "Male",
    class: 12,
    rollNo: 101,
    email: "john.doe@example.com",
    address: "123 Main Street, Cityville",
    phoneNumber: "123-456-7890",
  },
  {
    name: "Alice Smith",
    age: 22,
    gender: "Female",
    class: 11,
    rollNo: 202,
    email: "alice.smith@example.com",
    address: "456 Oak Avenue, Townsville",
    phoneNumber: "987-654-3210",
  },
  {
    name: "Bob Johnson",
    age: 28,
    gender: "Male",
    class: 10,
    rollNo: 303,
    email: "bob.johnson@example.com",
    address: "789 Pine Lane, Villagetown",
    phoneNumber: "456-789-0123",
  },
  {
    name: "Eva Martinez",
    age: 24,
    gender: "Female",
    class: 12,
    rollNo: 404,
    email: "eva.martinez@example.com",
    address: "567 Cedar Street, Hamletville",
    phoneNumber: "789-012-3456",
  },
];
export default myData;
